name: NL Cancel Test
on:
  workflow_dispatch:
    inputs:
      note:
        description: A free-text note
        required: false
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 180
